apiVersion: v2
name: ghostfolio-k8s
description: A Helm chart for deploying the Ghostfolio application to a Kubernetes cluster.
type: application

version: 0.2.0

# Current major version of the Ghostfolio. Not including the minor and patch version as this is an independent chart.
appVersion: "2"

# Bundled charts for convenience installations
dependencies:
  - name: postgresql
    version: 12.1.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.11.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled