# Default values for ghostfolio-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 32333

ghostfolio:
  repository: ghostfolio/ghostfolio
  tag: latest
  replicaCount: 1
  port: 3333
  pullPolicy: IfNotPresent
  env:
    - name: ACCESS_TOKEN_SALT
      value: ghostfolio
    - name: JWT_SECRET_KEY
      value: ghostfolio
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}
  serviceAccount:
    create: true
    automount: true
    name: ghostfolio-sa
    annotations: {}

postgresql:
  enabled: false
  auth:
    username: user
    password: ghostfolio

redis:
  enabled: false
  architecture: standalone
  auth:
    password: ghostfolio
