# Default values for ghostfolio-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 32333

ghostfolio:
  repository: ghostfolio/ghostfolio
  tag: latest
  replicaCount: 1
  port: 3333
  pullPolicy: IfNotPresent
  env: []
  serviceAccount:
    create: true
    automount: true
    name: ghostfolio-sa
    annotations: {}
  postgresql:
    connectionString: postgresql://user:ghostfolio@ghostfolio-postgresql/postgres?connect_timeout=300&sslmode=prefer
  redis:
    host: ghostfolio-redis-master
    password: ghostfolio
  jwtSecretKey: ghostfolio
  accessTokenSalt: ghostfolio
  # override the provided secret values with ones from an existing secret
  existingSecret: ""
  secretKeys:
    postgresqlConnectionString: ""
    redisPassword: ""
    jwtSecretKey: ""
    accessTokenSalt: ""
  resources: {}
  podAnnotations: {}
  podLabels: {}
  nodeSelector: {}
  affinity: {}
  tolerations: {}


postgresql:
  enabled: false
  auth:
    username: user
    password: ghostfolio
    # override the provided passwords with one from an existing secret
    existingSecret: ""
    secretKeys:
      adminPasswordKey: ""
      userPasswordKey: ""

redis:
  enabled: false
  architecture: standalone
  auth:
    password: ghostfolio
    # override the provided password with one from an existing secret
    existingSecret: ""
    existingSecretPasswordKey: ""