{{- if .Values.ghostfolio.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ghostfolio-k8s.serviceAccountName" . }}
  labels:
    {{- include "ghostfolio-k8s.labels" . | nindent 4 }}
  {{- with .Values.ghostfolio.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ghostfolio.serviceAccount.automount }}
{{- end }}
